#!/bin/bash

echo "cleaning the current folder"
./Allclean

echo "copying the NUOPC--WRF code..."
cp ../build/esmf_application .
cp ../build/namelist.rc .
cp ../jlocnmodel_code/* .

echo "running the NUOPC--WRF code..."
export ESMF_LOGLEVEL=TRACE
mpirun -np 7 ./esmf_application
