#!/bin/bash

echo "cleaning the current folder"
./Allclean

echo "copying the NUOPC--WRF code..."
cp ../build/esmf_application .
cp ../build/namelist.rc .
ln -s ../jlocnmodel_code .
cp -r ../test/02ESMF_EMOM/* .

echo "running the NUOPC--WRF code..."
export ESMF_LOGLEVEL=TRACE
mpirun -np 9 ./esmf_application
