

sNx = 5
sNy = 10

nSx = 1 # number of tiles per processor
nSy = 1

nPx = 2 # number of processors. 
nPy = 1

OLx = 3
OLy = 3


Nx = 10
Ny = 10
Nr = 5

coord = "latlon"

dx = 1.0
dy = 1.0

beg_x = 150.0
beg_y = 20.0




